CREATE DATABASE IF NOT EXISTS bookDB;
USE bookDB;

CREATE TABLE IF NOT EXISTS bookTable(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL
);
